bp-activity-subscription-functions.php

Removes hard-coded enforcement of the default default subscription level "no email," allowing users to filter `ass_default_subscription_level`. Fixes #71.

allow default default subscription levels other than "no email" 

---

bp-activity-subscription-functions.php

When a member joins a group by accepting an invitation or his
membership request is accepted, send the welcome email if configured
for the group. This improves welcome email coverage for non-public
groups and when a user is invited to a public group.

Send welcome email on acceptance of invitation or membership request.

---

bp-activity-subscription-digest.php

Allows other plugins to prevent the addition of specific activity item
IDs for specific users.

Add ass_digest_record_activity_allow  filter.

---

bp-activity-subscription-js.js
bp-activity-subscription-main.php

In my instance I have enabled the functionality within a custom courses component for Buddypress. To do so I had to modify the code to provide on all components.
A potential better solution is providing a setting for selecting from existing components rather than just enabling for everything.

Updates to enable support on custom components

---

admin.php

Seems about time for BPGES to stop revealing the deprecated "BuddyPress" top-level menu in Network Admin. Since BPGES already uses `bp_core_admin_hook()` to add its settings page (which was introduced in BP 1.5) perhaps it's also time to declare BP 1.5 as the minimum required version?

Move admin menu item to "Settings" menu

---

bp-activity-subscription-digest.php

The signature of the `bp_get_group_permalink` filter changed with BP 2.5, so the direct invocation of the filter using the old signature causes problems for functions expecting the extra parameter. 
I'm sure the filter was originally added as it was to avoid unnecessary lookups, but as the groups component has much better caching now, I wonder if some of this code could be simplified to use the groups functions rather than working around the ends.

Use bp_get_group_permalink() instead of filter.

---

screen-admin.php

This lets us leverage the `bp-ges-notice` BP mail type, which has been
around for a while but which has never been used.
@r-a-y I assume that this was an oversight when the BP mail stuff was added. Could you have a look to make sure this looks OK to you?

Use `ass_send_email()` for group notices.

---

bp-activity-subscription-digest.php
tests/testcases/digests.php

See #124.
I've chosen to put the filter inside of the `foreach activity_ids` loop, the idea being that you might decide to discard only items of a certain `type`, or whatever. This does mean that the filter can be run many times.
Thoughts?

"Stale" activity item failsafe for digests.

---

bp-activity-subscription-functions.php

Currently, if a user clicks on the "Unsubscribe" link from the email footer, it will unsubscribe the user from the group (or all groups depending on the setting) without any prior warning.
This can be a problem if email clients use some form of link auto-scanning as the user would have no idea that the group unsubscription has taken place.
This PR changes this behavior so a user form submission is required to confirm the group email unsubscription.  I've also added our textdomain to strings that previously did not have it.
In the future, it would be great to give theme authors the ability to change the default look of this page, but this isn't critical.

Require a form submission when clicking on the "Unsubscribe" link

---

bp-activity-subscription-functions.php

Hi Boone,
This PR fixes a fatal error when deleting an activity item not connected to any group subscription.
Steps to duplicate:
1. Post an update in the Activity directory.
2. Delete the newly-created activity item.
3. AJAX deletion hangs and fatal error is logged in `debug.log`

Fix fatal error when deleting activity items not connected to a group

---

admin.php
classes/class-bpges-queued-item.php
tests/testcases/subscription.php

Ran into a scenario where the same queued item can be recorded into the DB more than once.
This can occur if `ass_group_notification_activity()` is run twice, which can be caused when a plugin is modifying the activity item and resaving the activity entry.
In this PR, I opted to fix this by adding a unique index to the `wp_bpges_queued_items` DB table.  This prevents duplicates from being inserted.  I've also written a unit test outlining the bug.
After the PR is merged, we would also need to bump the updater.
Lastly, I fixed a typo for the `group_id` index using the wrong column name.  Up to you whether we should also add this to the updater routine, but since 3.9.x is still in development, we don't really have to do this.  We'll just have to fix this on our installs running 3.9.x.

Prevent duplicate entries from being recorded into the 'wp_bpges_queued_items' DB table

---

updater.php

If BuddyPress isn't active when GES is activated, GES will throw a fatal error because the GES updater uses the BuddyPress options API (`bp_get_option()`, `bp_update_option()`, `bp_add_option()`).
Let's bail from the updater if BP isn't active.  The updater will kick in when on various admin pages anyway.

Bail from updater if BuddyPress isn't available

---

bp-activity-subscription.php

Failure to pass `false` for this parameter can trigger the creation of
unneeded empty directories, which is especially a problem on multisite
installations where BPGES is network-activated.

When calling `wp_upload_dir()`, specify `$create_dir=false`.

---

bp-activity-subscription-functions.php

This allows for more specific `email_type` (ie email templates) to be used based on the specifics of the activity item. For example, this allows you to send all `bbp_topic_create` activity items to a specific template.

Allow BP email_type to be filtered.

---

screen-admin.php

On a group's "Manage > Members" page, there is a link located at the bottom of the page so super admins can change the email subscription for all members of a group.
This link did not change the email subscription for all group members though because the older `BP_Groups_Member::get_all_for_group()` call did not fetch all the group members correctly.
I've replaced that deprecated call with the `groups_get_group_members()` function, which correclty fetches all group members and fixes this issue.

Fix "update email subscription settings for all members to the default" link

---

bp-activity-subscription-functions.php

Saw this report on the wp.org forums - https://wordpress.org/support/topic/critical-error-63/
New installs of GES could potentially run into a fatal error if their install does not have the bbPress plugin activated due to the removal of the BP legacy forums and the use of a function that no longer exists.

Remove BuddyPress legacy forums function check

---

bp-activity-subscription-digest.php
bp-activity-subscription-functions.php
bp-activity-subscription-js.js
bp-activity-subscription-main.php
css/bp-activity-subscription-css.css
readme.txt
screen.php

This PR implements a new subscription options panel.
It uses the Van11y Accessible Modal Tooltip JS script:
https://github.com/nico3333fr/van11y-accessible-modal-tooltip-aria
Which means that the options panel is accessible via keyboard. The options can be navigated by tabbing through the options.
The new options panel is enabled by default for those using BP Nouveau and the older bp-default theme.
I did test the new options panel against all default WordPress Twenty themes as well and made the decision to disable it for the BP Legacy template pack due to layout issues (`overflow:hidden` for list items). However, you can force-enable the new options panel with a filter:
add_filter( 'bpges_use_new_options_panel', '__return_true' ); // Use '__return_false' to revert to the older panel.
I've …

Accessible subscription options panel

---

bp-activity-subscription-digest.php

See #166 
I'm choosing to use `add_filter()` instead of an inline call to `wpautop` in case anyone wants to change the behavior. @r-a-y This seem OK to you?

Run digest content through `wpautop()`.

---

bp-activity-subscription-digest.php

Previously, digest activity time was still displaying in GMT
* Unix timestamps know no timezone
* Now going directly from GMT time to formatted site time/date
* $timezone is maintained as Unix timestamp for passing to filter

Get activity time/date correctly in site timezone

---

bp-activity-subscription-functions.php
screen-admin.php
screen-notifications.php
templates/bpges/subscription-options-admin.php
templates/bpges/subscription-options-group.php

As discussed here: https://wordpress.org/support/topic/large-number-of-notifications-holding-up-ajax-response/ And here: https://wordpress.org/support/topic/working-on-changes-to-ass_group_notification_activity-function/
- I've altered the subscription options markup, and included the `bpges_wrap_input_labels` filter to control this markup (defaults to true).
- I've added the `bpges_email_from_name` and `bpges_email_from_email` filters to control the email from name / address.
- I've added the `bpges_notification_link` filter to control the link included in notifications.
Let me know if you've any questions.

Additional filters

---

admin.php

Currently, `ass_install_emails()` is hooked to the `'bp_core_install_emails'` hook:
https://github.com/boonebgorges/buddypress-group-email-subscription/blob/d322c0bfb053b9ee23d1e25a250717d1e506313a/admin.php#L378-L445
So whenever BuddyPress (or another plugin)
calls on the `bp_core_install_emails()` function, BPGES will always install their email templates without checking if they exist first.
Since BuddyPress has internally called on `bp_core_install_emails()` in their update routine in the past few releases, duplicate GES email templates were unintentionally being created:
* https://github.com/buddypress/buddypress/blob/c9b0e32face9b2e028184d7dad0ffd14fee87919/src/bp-core/bp-core-update.php#L636
* https://github.com/buddypress/buddypress/blob/c9b0e32face9b2e028184d7dad0ffd14fee87919/src/ …

Set $post_exists_check flag to true by default in ass_install_emails()

---

admin.php

This PR is the proper fix for #221.
All I can say is: Groan. I'm pretty sure I tested the previous fix and it was working. However, the default function parameter for `ass_install_emails()` no longer works properly when passed to an empty `do_action()` parameter call like the `'bp_core_install_emails'` hook. What seems to work is an anonymous function call on the `'bp_core_install_emails'` hook, so that's what I'm rolling with!

Only install our email templates if they do not exist
